apiVersion: v1
kind: Pod
metadata:
  name: tech-challenge-api
  labels:
    app: tech-challenge-api
spec:
  containers:
  - name: tech-challenge-api
    image: jpmarques2000/tech-challenge-api:latest
    ports:
    - containerPort: 80 